
-- PRINT THE DATA
SELECT *
FROM Portfolio_Project_001_SQL..flights

--PRINTING 10 LINES
SELECT AIRLINE, COUNT(AIRLINE) AS TOTAL_CANCELLED_FLIGHTS
FROM Portfolio_Project_001_SQL..flights
GROUP BY(AIRLINE)
ORDER BY TOTAL_CANCELLED_FLIGHTS DESC


-- CHECKING THE CANCELLED FLIGHTS BY MONTH
SELECT MONTH, COUNT(CANCELLED) AS TOTAL_CANCELLED_FLIGHTS
FROM Portfolio_Project_001_SQL..flights
WHERE CANCELLED = 1
GROUP BY MONTH
ORDER BY MONTH

-- CHECKING THE CANCELLED FLIGHTS BY CANCELLED CATEGORY
SELECT MONTH, CANCELLED, COUNT(CANCELLED) AS TOTAL_CANCELLED_FLIGHTS
FROM Portfolio_Project_001_SQL..flights
GROUP BY MONTH, CANCELLED
ORDER BY MONTH

-- CHECKING THE CANCELLED FLIGHTS AS PERCENTAGE BY MONTH
SELECT MONTH,
CAST(SUM(CASE WHEN CANCELLED = 1 THEN 1 ELSE 0 END) AS FLOAT)/CAST(COUNT(CANCELLED) AS FLOAT)*100 AS CANCELLED_FLIGHTS_PERCENTAGE,
COUNT(CANCELLED) AS TOTAL_FLIGHTS
FROM Portfolio_Project_001_SQL..flights
GROUP BY MONTH
ORDER BY CANCELLED_FLIGHTS_PERCENTAGE DESC

-- CHECKING THE CANCELLED FLIGHTS AS PERCENTAGE BY AIRLINE
SELECT AIRLINE,
CAST(SUM(CASE WHEN CANCELLED = 1 THEN 1 ELSE 0 END) AS FLOAT)/CAST(COUNT(CANCELLED) AS FLOAT)*100 AS CANCELLED_FLIGHTS_PERCENTAGE,
COUNT(CANCELLED) AS TOTAL_FLIGHTS
FROM Portfolio_Project_001_SQL..flights
GROUP BY AIRLINE
ORDER BY CANCELLED_FLIGHTS_PERCENTAGE DESC

-- FINDING THE NAME OF THE AIRLINE USING THE JOIN
SELECT airlines.AIRLINE,
CAST(SUM(CASE WHEN flights.CANCELLED = 1 THEN 1 ELSE 0 END) AS FLOAT)/CAST(COUNT(flights.CANCELLED) AS FLOAT)*100 AS CANCELLED_FLIGHTS_PERCENTAGE,
COUNT(flights.CANCELLED) AS TOTAL_FLIGHTS
FROM Portfolio_Project_001_SQL..flights flights
LEFT JOIN Portfolio_Project_001_SQL..airlines$ airlines 
ON flights.AIRLINE = airlines.IATA_CODE
GROUP BY airlines.AIRLINE
ORDER BY CANCELLED_FLIGHTS_PERCENTAGE DESC

--PRINTING AIRLINE FILE DATA
SELECT * FROM Portfolio_Project_001_SQL..airlines$;

-- CHECKING THE CANCELLED FLIGHTS BY ORIGIN_AIRPORT AND DESTINATION_AIRPORT
SELECT ORIGIN_AIRPORT, DESTINATION_AIRPORT, COUNT(CANCELLED) AS TOTAL_CANCELLED_FLIGHTS
FROM Portfolio_Project_001_SQL..flights
WHERE CANCELLED = 1
GROUP BY ORIGIN_AIRPORT, DESTINATION_AIRPORT
ORDER BY TOTAL_CANCELLED_FLIGHTS DESC


-- CHECKING THE CANCELLED FLIGHTS BY ORIGIN_AIRPORT NAME AND DESTINATION_AIRPORT NAME
SELECT airports1.AIRPORT AS LOCATION_FROM, airports2.AIRPORT AS LOCATION_TO, COUNT(flights.CANCELLED) AS TOTAL_CANCELLED_FLIGHTS
FROM Portfolio_Project_001_SQL..flights flights
INNER JOIN Portfolio_Project_001_SQL..airports$ airports1
ON flights.ORIGIN_AIRPORT = airports1.IATA_CODE
INNER JOIN Portfolio_Project_001_SQL..airports$ airports2
ON flights.DESTINATION_AIRPORT = airports2.IATA_CODE
WHERE flights.CANCELLED = 1
GROUP BY airports1.AIRPORT, airports2.AIRPORT
ORDER BY TOTAL_CANCELLED_FLIGHTS DESC

-- CHECKING THE CANCELLED FLIGHTS BY ORIGIN CITY NAME AND DESTINATION CITY NAME
SELECT airports1.CITY AS LOCATION_FROM, airports2.CITY AS LOCATION_TO, COUNT(flights.CANCELLED) AS TOTAL_CANCELLED_FLIGHTS
FROM Portfolio_Project_001_SQL..flights flights
INNER JOIN Portfolio_Project_001_SQL..airports$ airports1
ON flights.ORIGIN_AIRPORT = airports1.IATA_CODE
INNER JOIN Portfolio_Project_001_SQL..airports$ airports2
ON flights.DESTINATION_AIRPORT = airports2.IATA_CODE
WHERE flights.CANCELLED = 1
GROUP BY airports1.CITY, airports2.CITY
ORDER BY TOTAL_CANCELLED_FLIGHTS DESC


-- CHECKING THE CANCELLED FLIGHTS BY ORIGIN CITY NAME
SELECT airports1.CITY AS LOCATION_FROM, COUNT(flights.CANCELLED) AS TOTAL_CANCELLED_FLIGHTS
FROM Portfolio_Project_001_SQL..flights flights
INNER JOIN Portfolio_Project_001_SQL..airports$ airports1
ON flights.ORIGIN_AIRPORT = airports1.IATA_CODE
WHERE flights.CANCELLED = 1
GROUP BY airports1.CITY
ORDER BY TOTAL_CANCELLED_FLIGHTS DESC

-- CHECKING THE CANCELLED FLIGHTS BY DESTINATION CITY NAME
SELECT airports1.CITY AS LOCATION_TO, COUNT(flights.CANCELLED) AS TOTAL_CANCELLED_FLIGHTS
FROM Portfolio_Project_001_SQL..flights flights
INNER JOIN Portfolio_Project_001_SQL..airports$ airports1
ON flights.DESTINATION_AIRPORT = airports1.IATA_CODE
WHERE flights.CANCELLED = 1
GROUP BY airports1.CITY
ORDER BY TOTAL_CANCELLED_FLIGHTS DESC

--FINDING THE THIRD MOST FLIGHT CANCELLED TO - DESTINATION
SELECT airports1.CITY AS LOCATION_TO, COUNT(flights.CANCELLED) AS TOTAL_CANCELLED_FLIGHTS
FROM Portfolio_Project_001_SQL..flights flights
INNER JOIN Portfolio_Project_001_SQL..airports$ airports1
ON flights.DESTINATION_AIRPORT = airports1.IATA_CODE
WHERE flights.CANCELLED = 1
GROUP BY airports1.CITY
ORDER BY TOTAL_CANCELLED_FLIGHTS DESC OFFSET 2 ROWS FETCH NEXT 1 ROWS ONLY;